apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    name: database-config
    group: db
data:
  POSTGRES_DB: devops
  POSTGRES_USER: post
  POSTGRES_PASSWORD: gresql # TODO: injection of secrets (e.g. as k8s secret + kubectl --environment=DB_PW:)
