apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    name: database-service
    group: db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg-svc
      port: 5432
      targetPort: pg-deploy
      protocol: TCP
