apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    name: devops-app
    app: node
    group: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
        group: app
        type: app
    spec:
      imagePullSecrets:
        - name: dpr-secret
      initContainers:
        - name: database-migration
          image: ghcr.io/kelzenberg/devops-app:master
          imagePullPolicy: Always
          command: [/flyway/flyway]
          args:
            [
              "-connectRetries=60",
              "-locations=filesystem:/flyway/sql",
              "migrate",
            ]
          envFrom:
            - configMapRef:
                name: database-config
            - configMapRef:
                name: migration-config
          resources:
            requests:
              cpu: 20m
              memory: 64M
            limits:
              memory: 128M
      containers:
        - name: devops-app
          image: ghcr.io/kelzenberg/devops-app:master
          imagePullPolicy: Always
          command: [node]
          args: ["dist/index.js"]
          ports:
            - name: app-deploy
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: database-config
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 100m
              memory: 128M
