apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    name: devops-app
    app: node
    group: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
        group: app
        type: app
    spec:
      imagePullSecrets:
        - name: dpr-secret
      initContainers:
        - name: database-readiness
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          command: [
              "sh",
              "-c",
              "until pg_isready -h database-service.$(K8S_NAMESPACE).svc.cluster.local -U $(POSTGRES_USER) -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
          envFrom:
            - configMapRef:
                name: database-config
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: database-migration
          image: ghcr.io/kelzenberg/devops-app:master
          imagePullPolicy: Always
          command: [/flyway/flyway]
          args:
            [
              "-connectRetries=60",
              "-locations=filesystem:/flyway/sql",
              "migrate",
            ]
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLYWAY_URL
              value: jdbc:postgresql://database-service.$(K8S_NAMESPACE).svc.cluster.local:5432/$(POSTGRES_DB)
            - name: FLYWAY_USER
              value: $(POSTGRES_USER)
          resources:
            requests:
              cpu: 20m
              memory: 64M
            limits:
              memory: 128M
      containers:
        - name: devops-app
          image: ghcr.io/kelzenberg/devops-app:master
          imagePullPolicy: Always
          command: [node]
          args: ["dist/index.js"]
          ports:
            - name: app-deploy
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_HOST
              value: database-service.$(K8S_NAMESPACE).svc.cluster.local:5432
            - name: NODE_ENV
              value: $(K8S_NAMESPACE)
          livenessProbe:
            httpGet:
              path: /liveness
              port: app-deploy
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: app-deploy
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 100m
              memory: 128M
